In [20]:
using LinearAlgebra, Test, Plots, Random, Distributions, Printf
pyplot()

nothing;

In [21]:
function strong_kron(A,B ::Array{T,N}) where {T<:Number,N}
    @assert size(A,3) == size(B,1)
    α=size(A,1)
    μ=size(A,2)
    β=size(A,3)
    ρ=size(B,2)
    γ=size(B,3)
    
    A = reshape(A,α*μ,β)
    B = reshape(B,β,ρ*γ)
    
    C = A*B
    
    C=reshape(C,α,μ*ρ,γ)
    
    return C
end
nothing;

In [22]:
function evaluate(S,n)
    N = length(S)
    A = copy(S[1])
    for j ∈ 2:N
        A=strong_kron(A,copy(S[j]))
    end
    A = reshape(A,n...)
    return A
end

evaluate (generic function with 1 method)

Matrix U0

matrix U1 to UL-1

In [23]:
U_temp = zeros(3,2,3)
#α1 =1
U_temp[1,1,1] = 1
U_temp[1,2,1] = 1
#α1=2, il=1
U_temp[2,1,1] = -0.5
U_temp[2,1,2] = 0.5
#α1=2, il=2
U_temp[2,2,1] = 0.5
U_temp[2,2,2] = 0.5


#α1=3 il=1
U_temp[3,1,1] = 0
U_temp[3,1,2] = -0.75
U_temp[3,1,3] = 0.25

#α1=3 il=2
U_temp[3,2,1] = 0
U_temp[3,2,2] = 0.75
U_temp[3,2,3] = 0.25
U_temp

3×2×3 Array{Float64, 3}:
[:, :, 1] =
  1.0  1.0
 -0.5  0.5
  0.0  0.0

[:, :, 2] =
  0.0   0.0
  0.5   0.5
 -0.75  0.75

[:, :, 3] =
 0.0   0.0
 0.0   0.0
 0.25  0.25

In [24]:
f(t) = (t-1)/2

println((f(-1)+f(1))*1/2,' ',(f(1)-f(-1))*1/2)
println(f(1))
println(f(-1))

-0.5 0.5
0.0
-1.0


In [25]:
U_L = zeros(3,2,2)
#α1=1
U_L[1,1,1] = 1
U_L[1,2,1] = 1

#α1=2 il=1
U_L[2,1,1] =-0.5
U_L[2,1,2] =0.5

#α1=2 il=2
U_L[2,2,1] = 0.5
U_L[2,2,2] = 0.5

#α1=3 il=1
U_L[3,1,1] = 0.25
U_L[3,1,2] = -0.75


#α1=3 il=2
U_L[3,2,1] = 0.25
U_L[3,2,2] = 0.75

0.75

In [26]:
function quadpol(L,a,b,c)
    U_0 = zeros(1,1,3)
    U_0[1,1,1] = a/4+b/2+c+a/12
    U_0[1,1,2] = (a+b)/2
    U_0[1,1,3] = a/6
    U_decomp = [U_0]
    
    for i = 1:L-1
        push!(U_decomp,U_temp)
    end
    push!(U_decomp,U_L)
    
    U_last = ones(2,1,1)
    push!(U_decomp,U_last)
    return U_decomp
end

quadpol (generic function with 1 method)

In [27]:
L=10
a=1.
b=-2.
c=2.
U_test = quadpol(L,a,b,c)

12-element Vector{Array{Float64, 3}}:
 [1.3333333333333333;;; -0.5;;; 0.16666666666666666]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.25 0.25;;; 0.0 0.0; 0.5 0.5; -0.75 0.75]
 [1.0; 1

In [28]:
function nodeval(U,s)
    d = length(U)
    n = length(s)
    
    U_trail = ones(2,n)
    for i = 1:n
        U_trail[2,i] = s[i]
    end
    println(U_trail)
    
    V = U_trail
    println(V)
    U[d] = reshape(V,2,n,1)
    
    return U
end

nodeval (generic function with 1 method)

In [29]:
U_a = nodeval(copy(U_test),[-1,1])

[1.0 1.0; -1.0 1.0]
[1.0 1.0; -1.0 1.0]


12-element Vector{Array{Float64, 3}}:
 [1.3333333333333333;;; -0.5;;; 0.16666666666666666]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.0 0.0;;; 0.0 0.0; 0.5 0.5; -0.75 0.75;;; 0.0 0.0; 0.0 0.0; 0.25 0.25]
 [1.0 1.0; -0.5 0.5; 0.25 0.25;;; 0.0 0.0; 0.5 0.5; -0.75 0.75]
 [1.0 1.

In [30]:
ndim = [size(U_a[i],2) for i = 1:length(U_a)]
big_U = evaluate(U_a,ndim)
rev = reverse(1:L+2)
big_U=permutedims(big_U,rev)

2×2×2×2×2×2×2×2×2×2×2×1 Array{Float64, 12}:
[:, :, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] =
 2.0      1.99805
 1.99805  1.9961

[:, :, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.9961   1.99415
 1.99415  1.9922

[:, :, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.9922   1.99026
 1.99026  1.98832

[:, :, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.98832  1.98637
 1.98637  1.98444

[:, :, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.98444  1.9825
 1.9825   1.98056

[:, :, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.98056  1.97863
 1.97863  1.9767

[:, :, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.9767   1.97477
 1.97477  1.97284

[:, :, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.97284  1.97092
 1.97092  1.96899

[:, :, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1] =
 1.96899  1.96707
 1.96707  1.96515

[:, :, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1] =
 1.96515  1.96323
 1.96323  1.96132

[:, :, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1] =
 1.96132  1.9594
 1.9594   1.95749

[:, :, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1] =
 1.95749  1.95558
 1.95558  1.95367

[:, :, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1] =
 1.95367  

In [31]:
p = prod(ndim)
u_a = reshape(big_U,p)
h = 2. ^(-L)
u(t) = a*t^2+b*t+c

u_b = [u(0)]

for i=1:(2^L)-1
    #println(u(h*i))
    push!(u_b,u(h*i))
    push!(u_b,u(h*i))
end

push!(u_b,u(1))

println(norm(u_a-u_b))
println(norm(u_a-u_b,Inf))

0.0
0.0


In [32]:
function trig(L,a,b,c)
    U_0 = zeros(1,1,2)
    U_0[1,1,1] = a*cos(π*c) + b*sin(π*c)
    U_0[1,1,2] = b*cos(π*c) - a*sin(π*c)
    
    U_decomp = [U_0]
    temp = π*c
    for i = 1:L-1
        temp = temp/2   #2^-l pi c
        U_l = zeros(2,2,2)
        U_l[1,1,1] = cos(temp)
        U_l[1,1,2] = sin(temp)
        
        U_l[1,2,1] = cos(temp)
        U_l[1,2,2] = -sin(temp)
        
        U_l[2,1,1] = -sin(temp)
        U_l[2,1,2] = cos(temp)
        
        U_l[2,2,1] = sin(temp)
        U_l[2,2,2] = cos(temp)
        
        push!(U_decomp,U_l)
    end
    U_L = zeros(2,2,2)
    
    U_L[1,1,1] = (cos(temp*0)+cos(temp*(-1)))/2  #(t-1)/2
    U_L[1,1,2] = (cos(temp*0)-cos(temp*(-1)))/2 
    
    
    U_L[1,2,1] = (cos(temp*1)+cos(temp*(0)))/2  #(t+1)/2
    U_L[1,2,2] = (cos(temp*1)-cos(temp*(0)))/2
    
    U_L[2,1,1] = (sin(temp*0)+sin(temp*(-1)))/2 #(t-1)/2
    U_L[2,1,2] = (sin(temp*0)-sin(temp*(-1)))/2
    
    U_L[2,2,1] = (sin(temp*1)+sin(temp*(0)))/2  #(t+1)/2
    U_L[2,2,2] = (sin(temp*1)-sin(temp*(0)))/2
   
    push!(U_decomp,U_L)
    
    U_last = ones(2,1,1)
    push!(U_decomp,U_last)
    return U_decomp
end
        

trig (generic function with 1 method)

In [39]:
L =10
a1 = 1
b1=2
c1=7
V_test = trig(L,a1,b1,c1)

12-element Vector{Array{Float64, 3}}:
 [-0.9999999999999983;;; -2.000000000000001]
 [-4.286263797015736e-16 -4.286263797015736e-16; 1.0 -1.0;;; -1.0 1.0; -4.286263797015736e-16 -4.286263797015736e-16]
 [0.7071067811865474 0.7071067811865474; 0.7071067811865477 -0.7071067811865477;;; -0.7071067811865477 0.7071067811865477; 0.7071067811865474 0.7071067811865474]
 [-0.9238795325112867 -0.9238795325112867; -0.3826834323650899 0.3826834323650899;;; 0.3826834323650899 -0.3826834323650899; -0.9238795325112867 -0.9238795325112867]
 [0.19509032201612833 0.19509032201612833; -0.9807852804032304 0.9807852804032304;;; 0.9807852804032304 -0.9807852804032304; 0.19509032201612833 0.19509032201612833]
 [0.773010453362737 0.773010453362737; -0.6343932841636455 0.6343932841636455;;; 0.6343932841636455 -0.6343932841636455; 0.773010453362737 0.773010453362737]
 [0.9415440651830208 0.9415440651830208; -0.33688985339222005 0.33688985339222005;;; 0.33688985339222005 -0.33688985339222005; 0.9415440651830208 0

In [40]:
V_a = nodeval(copy(V_test),[-1,1])


[1.0 1.0; -1.0 1.0]
[1.0 1.0; -1.0 1.0]


12-element Vector{Array{Float64, 3}}:
 [-0.9999999999999983;;; -2.000000000000001]
 [-4.286263797015736e-16 -4.286263797015736e-16; 1.0 -1.0;;; -1.0 1.0; -4.286263797015736e-16 -4.286263797015736e-16]
 [0.7071067811865474 0.7071067811865474; 0.7071067811865477 -0.7071067811865477;;; -0.7071067811865477 0.7071067811865477; 0.7071067811865474 0.7071067811865474]
 [-0.9238795325112867 -0.9238795325112867; -0.3826834323650899 0.3826834323650899;;; 0.3826834323650899 -0.3826834323650899; -0.9238795325112867 -0.9238795325112867]
 [0.19509032201612833 0.19509032201612833; -0.9807852804032304 0.9807852804032304;;; 0.9807852804032304 -0.9807852804032304; 0.19509032201612833 0.19509032201612833]
 [0.773010453362737 0.773010453362737; -0.6343932841636455 0.6343932841636455;;; 0.6343932841636455 -0.6343932841636455; 0.773010453362737 0.773010453362737]
 [0.9415440651830208 0.9415440651830208; -0.33688985339222005 0.33688985339222005;;; 0.33688985339222005 -0.33688985339222005; 0.9415440651830208 0

In [41]:
ndim = [size(V_a[i],2) for i = 1:length(V_a)]
big_V = evaluate(V_a,ndim)
rev = reverse(1:L+2)
big_V=permutedims(big_V,rev)

2×2×2×2×2×2×2×2×2×2×2×1 Array{Float64, 12}:
[:, :, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.0      1.08495
 1.08495  1.16791

[:, :, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.16791  1.24871
 1.24871  1.3272

[:, :, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.3272   1.40325
 1.40325  1.47671

[:, :, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1] =
 1.47671  1.54744
 1.54744  1.61532

[:, :, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.61532  1.68023
 1.68023  1.74203

[:, :, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.74203  1.80062
 1.80062  1.85588

[:, :, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.85588  1.90773
 1.90773  1.95605

[:, :, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1] =
 1.95605  2.00077
 2.00077  2.0418

[:, :, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1] =
 2.0418   2.07906
 2.07906  2.11248

[:, :, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1] =
 2.11248  2.14201
 2.14201  2.16759

[:, :, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1] =
 2.16759  2.18917
 2.18917  2.20671

[:, :, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1] =
 2.20671  2.22018
 2.22018  2.22956

[:, :, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1] =
 2.2295

In [42]:
p = prod(ndim)
v_a = reshape(big_V,p)
h = 2. ^(-L)
v(t) = a1*cos(2*π*c1*t) + b1*sin(2*π*c1*t)

v_b = [v(0)]

for i=1:(2^L)-1
    #println(u(h*i))
    push!(v_b,v(h*i))
    push!(v_b,v(h*i))
end

push!(v_b,v(1))

println(norm(v_a-v_b))
println(norm(v_a-v_b,Inf))

9.175868342227904e-14
7.993605777301127e-15


In [43]:
v_a

2048-element Vector{Float64}:
 1.0000000000000002
 1.0849542416225273
 1.0849542416225273
 1.167907236871658
 1.167907236871658
 1.248705975256686
 1.2487059752566863
 1.327201419909544
 1.3272014199095439
 1.4032487824899371
 1.403248782489937
 1.4767077902538812
 1.4767077902538814
 ⋮
 0.4572451518358192
 0.5508075028255679
 0.550807502825568
 0.6433538648683351
 0.6433538648683352
 0.7347135320815097
 0.7347135320815096
 0.8247179874938947
 0.8247179874938947
 0.9132012138827602
 0.9132012138827603
 0.9999999999999967

In [44]:
v_b

2048-element Vector{Float64}:
 1.0
 1.084954241622527
 1.084954241622527
 1.1679072368716579
 1.1679072368716579
 1.2487059752566858
 1.2487059752566858
 1.3272014199095437
 1.3272014199095437
 1.4032487824899371
 1.4032487824899371
 1.4767077902538812
 1.4767077902538812
 ⋮
 0.45724515183582204
 0.5508075028255729
 0.5508075028255729
 0.6433538648683421
 0.6433538648683421
 0.7347135320815035
 0.7347135320815035
 0.8247179874938906
 0.8247179874938906
 0.9132012138827582
 0.9132012138827582
 0.9999999999999966